In [1]:
import pandas as pd

trucks = pd.read_csv('truck_event_text_partition.csv', index_col = 0)

In [2]:
### RENAME()

trucks.columns

Index(['driverId', 'truckId', 'eventTime', 'eventType', 'longitude',
       'latitude', 'eventKey', 'CorrelationId', 'driverName', 'routeId',
       'routeName', 'eventDate'],
      dtype='object')

In [4]:
trucks.rename(columns={'driverId': 'Identification'})

,Identification,truckId,eventTime,eventType,longitude,latitude,eventKey,CorrelationId,driverName,routeId,routeName,eventDate
0,14,25,59:21.4,Normal,-94.58,37.03,14|25|9223370572464814373,3.660000e+18,Adis Cesir,160405074,Joplin to Kansas City Route 2,2016-05-27-22
1,18,16,59:21.7,Normal,-89.66,39.78,18|16|9223370572464814089,3.660000e+18,Grant Liu,1565885487,Springfield to KC Via Hanibal,2016-05-27-22
2,27,105,59:21.7,Normal,-90.21,38.65,27|105|9223370572464814070,3.660000e+18,Mark Lochbihler,1325562373,Springfield to KC Via Columbia Route 2,2016-05-27-22
3,11,74,59:21.7,Normal,-90.20,38.65,11|74|9223370572464814123,3.660000e+18,Jamie Engesser,1567254452,Saint Louis to Memphis Route2,2016-05-27-22
4,22,87,59:21.7,Normal,-90.04,35.19,22|87|9223370572464814101,3.660000e+18,Nadeem Asghar,1198242881,Saint Louis to Chicago Route2,2016-05-27-22
...,...,...,...,...,...,...,...,...,...,...,...,...
17070,11,27,12:23.1,Normal,-90.20,38.65,11|27|9223370571956432681,1.000000e+03,Jamie Engesser,1198242881,Saint Louis to Chicago Route2,2016-06-02-20
17071,16,46,12:24.0,Normal,-94.35,38.33,16|46|9223370571956431821,1.000000e+03,Tom McCuch,160405074,Joplin to Kansas City Route 2,2016-06-02-20
17072,18,49,12:23.7,Normal,-90.52,39.71,18|49|9223370571956432141,1.000000e+03,Grant Liu,1565885487,Springfield to KC Via Hanibal,2016-06-02-20
17073,10,39,12:23.8,Normal,-93.34,37.21,10|39|9223370571956431961,1.000000e+03,George Vetticaden,1390372503,Saint Louis to Tulsa,2016-06-02-20
17074,19,100,12:24.0,Normal,-97.37,36.79,19|100|9223370571956431810,1.000000e+03,Ajay Singh,1962261785,Wichita to Little Rock.kml,2016-06-02-20

In [5]:
trucks.rename(index={0:'firstEntry', 1:'secondEntry'})

,driverId,truckId,eventTime,eventType,longitude,latitude,eventKey,CorrelationId,driverName,routeId,routeName,eventDate
firstEntry,14,25,59:21.4,Normal,-94.58,37.03,14|25|9223370572464814373,3.660000e+18,Adis Cesir,160405074,Joplin to Kansas City Route 2,2016-05-27-22
secondEntry,18,16,59:21.7,Normal,-89.66,39.78,18|16|9223370572464814089,3.660000e+18,Grant Liu,1565885487,Springfield to KC Via Hanibal,2016-05-27-22
2,27,105,59:21.7,Normal,-90.21,38.65,27|105|9223370572464814070,3.660000e+18,Mark Lochbihler,1325562373,Springfield to KC Via Columbia Route 2,2016-05-27-22
3,11,74,59:21.7,Normal,-90.20,38.65,11|74|9223370572464814123,3.660000e+18,Jamie Engesser,1567254452,Saint Louis to Memphis Route2,2016-05-27-22
4,22,87,59:21.7,Normal,-90.04,35.19,22|87|9223370572464814101,3.660000e+18,Nadeem Asghar,1198242881,Saint Louis to Chicago Route2,2016-05-27-22
...,...,...,...,...,...,...,...,...,...,...,...,...
17070,11,27,12:23.1,Normal,-90.20,38.65,11|27|9223370571956432681,1.000000e+03,Jamie Engesser,1198242881,Saint Louis to Chicago Route2,2016-06-02-20
17071,16,46,12:24.0,Normal,-94.35,38.33,16|46|9223370571956431821,1.000000e+03,Tom McCuch,160405074,Joplin to Kansas City Route 2,2016-06-02-20
17072,18,49,12:23.7,Normal,-90.52,39.71,18|49|9223370571956432141,1.000000e+03,Grant Liu,1565885487,Springfield to KC Via Hanibal,2016-06-02-20
17073,10,39,12:23.8,Normal,-93.34,37.21,10|39|9223370571956431961,1.000000e+03,George Vetticaden,1390372503,Saint Louis to Tulsa,2016-06-02-20
17074,19,100,12:24.0,Normal,-97.37,36.79,19|100|9223370571956431810,1.000000e+03,Ajay Singh,1962261785,Wichita to Little Rock.kml,2016-06-02-20

In [6]:
### CONCAT

'''canadian_youtube = pd.read_csv("../input/youtube-new/CAvideos.csv")
british_youtube = pd.read_csv("../input/youtube-new/GBvideos.csv")

pd.concat([canadian_youtube, british_youtube])'''

'canadian_youtube = pd.read_csv("../input/youtube-new/CAvideos.csv")\nbritish_youtube = pd.read_csv("../input/youtube-new/GBvideos.csv")\n\npd.concat([canadian_youtube, british_youtube])'

In [7]:
### JOIN  ##

'''left = canadian_youtube.set_index(['title', 'trending_date'])
right = british_youtube.set_index(['title', 'trending_date'])

left.join(right, lsuffix='_CAN', rsuffix='_UK')'''

"left = canadian_youtube.set_index(['title', 'trending_date'])\nright = british_youtube.set_index(['title', 'trending_date'])\n\nleft.join(right, lsuffix='_CAN', rsuffix='_UK')"

In [8]:
## powerlifting_combined = powerlifting_meets.set_index("MeetID").join(powerlifting_competitors.set_index("MeetID"))