In [1]:
import pandas as pd

trucks = pd.read_csv('truck_event_text_partition.csv', index_col = 0)

In [2]:
trucks.columns

Index(['driverId', 'truckId', 'eventTime', 'eventType', 'longitude',
       'latitude', 'eventKey', 'CorrelationId', 'driverName', 'routeId',
       'routeName', 'eventDate'],
      dtype='object')

In [3]:
trucks.driverName.value_counts()

Grant Liu               751
Teddy Choi              750
Nadeem Asghar           749
Jeff Markham            748
Eric Mizell             748
Rommel Garcia           747
Ryan Templeton          747
Paul Codding            746
Adis Cesir              746
Chris Harris            746
Joe Niemiec             746
Tom McCuch              745
Ajay Singh              745
Don Hilborn             745
Adam Diaz               745
Olivier Renault         744
Michael Aube            744
Jean-Philippe Player    743
Mark Lochbihler         742
Rohit Bakshi            741
Dan Rice                741
George Vetticaden       730
Jamie Engesser          686
Name: driverName, dtype: int64

In [21]:
trucks.groupby('driverName').driverName.count()

driverName
Adam Diaz               745
Adis Cesir              746
Ajay Singh              745
Chris Harris            746
Dan Rice                741
Don Hilborn             745
Eric Mizell             748
George Vetticaden       730
Grant Liu               751
Jamie Engesser          686
Jean-Philippe Player    743
Jeff Markham            748
Joe Niemiec             746
Mark Lochbihler         742
Michael Aube            744
Nadeem Asghar           749
Olivier Renault         744
Paul Codding            746
Rohit Bakshi            741
Rommel Garcia           747
Ryan Templeton          747
Teddy Choi              750
Tom McCuch              745
Name: driverName, dtype: int64

In [22]:
### ES LO MISMO QUE HACER ###

trucks.groupby('driverName').size()

driverName
Adam Diaz               745
Adis Cesir              746
Ajay Singh              745
Chris Harris            746
Dan Rice                741
Don Hilborn             745
Eric Mizell             748
George Vetticaden       730
Grant Liu               751
Jamie Engesser          686
Jean-Philippe Player    743
Jeff Markham            748
Joe Niemiec             746
Mark Lochbihler         742
Michael Aube            744
Nadeem Asghar           749
Olivier Renault         744
Paul Codding            746
Rohit Bakshi            741
Rommel Garcia           747
Ryan Templeton          747
Teddy Choi              750
Tom McCuch              745
dtype: int64

In [7]:
trucks.groupby('driverName').count()

,driverId,truckId,eventTime,eventType,longitude,latitude,eventKey,CorrelationId,routeId,routeName,eventDate
driverName,,,,,,,,,,,
Adam Diaz,745,745,745,745,745,745,745,745,745,745,745
Adis Cesir,746,746,746,746,746,746,746,746,746,746,746
Ajay Singh,745,745,745,745,745,745,745,745,745,745,745
Chris Harris,746,746,746,746,746,746,746,746,746,746,746
Dan Rice,741,741,741,741,741,741,741,741,741,741,741
Don Hilborn,745,745,745,745,745,745,745,745,745,745,745
Eric Mizell,748,748,748,748,748,748,748,748,748,748,748
George Vetticaden,730,730,730,730,730,730,730,730,730,730,730
Grant Liu,751,751,751,751,751,751,751,751,751,751,751
Jamie Engesser,686,686,686,686,686,686,686,686,686,686,686
Jean-Philippe Player,743,743,743,743,743,743,743,743,743,743,743
Jeff Markham,748,748,748,748,748,748,748,748,748,748,748
Joe Niemiec,746,746,746,746,746,746,746,746,746,746,746
Mark Lochbihler,742,742,742,742,742,742,742,742,742,742,742
Michael Aube,744,744,744,744,744,744,744,744,744,744,744
Nadeem Asghar,749,749,749,749,749,749,749,749,749,749,749
Olivier Renault,744,744,744,744,744,744,744,744,744,744,744
Paul Codding,746,746,746,746,746,746,746,746,746,746,746
Rohit Bakshi,741,741,741,741,741,741,741,741,741,741,741
Rommel Garcia,747,747,747,747,747,747,747,747,747,747,747
Ryan Templeton,747,747,747,747,747,747,747,747,747,747,747
Teddy Choi,750,750,750,750,750,750,750,750,750,750,750
Tom McCuch,745,745,745,745,745,745,745,745,745,745,745

In [9]:
### Podemos hacer otras cosas como mirar el mínimo/máximo ID del cminón para cada conductor

trucks.groupby('driverName').truckId.max()

driverName
Adam Diaz                93
Adis Cesir               56
Ajay Singh              109
Chris Harris             79
Dan Rice                 95
Don Hilborn             102
Eric Mizell              97
George Vetticaden        85
Grant Liu               104
Jamie Engesser           98
Jean-Philippe Player    106
Jeff Markham            109
Joe Niemiec              89
Mark Lochbihler         105
Michael Aube             57
Nadeem Asghar            87
Olivier Renault          90
Paul Codding            104
Rohit Bakshi             92
Rommel Garcia            86
Ryan Templeton           84
Teddy Choi              108
Tom McCuch               77
Name: truckId, dtype: int64

In [11]:
## Se puede agrupar por más de una categoría


trucks.groupby(['driverName', 'routeName']).truckId.count()

driverName  routeName
Adam Diaz   Des Moines to Chicago Route 2      11
            Joplin to Kansas City Route 2     109
            Memphis to Little Rock            248
            Memphis to Little Rock Route 2    133
            Saint Louis to Memphis            244
                                             ...
Teddy Choi  Wichita to Little Rock Route 2    750
Tom McCuch   Saint Louis to Chicago           134
            Joplin to Kansas City Route 2     255
            Peoria to Ceder Rapids Route 2    248
            Saint Louis to Memphis            108
Name: truckId, Length: 69, dtype: int64

In [12]:
## Podemos usar el método --> AGG <-- para aplicar varias operaciones con grupby


trucks.groupby('driverName').truckId.agg([min, max, len])

                      min  max  len
driverName
Adam Diaz              26   93  745
Adis Cesir             15   56  746
Ajay Singh             26  109  745
Chris Harris           20   79  746
Dan Rice               18   95  741
Don Hilborn            61  102  745
Eric Mizell            15   97  748
George Vetticaden      23   85  730
Grant Liu              11  104  751
Jamie Engesser         19   98  686
Jean-Philippe Player   17  106  743
Jeff Markham           21  109  748
Joe Niemiec            10   89  746
Mark Lochbihler        11  105  742
Michael Aube           17   57  744
Nadeem Asghar          24   87  749
Olivier Renault        34   90  744
Paul Codding           22  104  746
Rohit Bakshi           32   92  741
Rommel Garcia          18   86  747
Ryan Templeton         21   84  747
Teddy Choi             16  108  750
Tom McCuch             12   77  745

In [15]:
## SORTING ###

ordenada = trucks.groupby('driverName').truckId.agg([min, max, len])
ordenada.sort_values(by='len')

                      min  max  len
driverName
Jamie Engesser         19   98  686
George Vetticaden      23   85  730
Rohit Bakshi           32   92  741
Dan Rice               18   95  741
Mark Lochbihler        11  105  742
Jean-Philippe Player   17  106  743
Olivier Renault        34   90  744
Michael Aube           17   57  744
Adam Diaz              26   93  745
Tom McCuch             12   77  745
Don Hilborn            61  102  745
Ajay Singh             26  109  745
Joe Niemiec            10   89  746
Chris Harris           20   79  746
Paul Codding           22  104  746
Adis Cesir             15   56  746
Rommel Garcia          18   86  747
Ryan Templeton         21   84  747
Eric Mizell            15   97  748
Jeff Markham           21  109  748
Nadeem Asghar          24   87  749
Teddy Choi             16  108  750
Grant Liu              11  104  751

In [16]:
ordenada.sort_values(by='len', ascending = False)

                      min  max  len
driverName
Grant Liu              11  104  751
Teddy Choi             16  108  750
Nadeem Asghar          24   87  749
Jeff Markham           21  109  748
Eric Mizell            15   97  748
Ryan Templeton         21   84  747
Rommel Garcia          18   86  747
Adis Cesir             15   56  746
Chris Harris           20   79  746
Paul Codding           22  104  746
Joe Niemiec            10   89  746
Adam Diaz              26   93  745
Don Hilborn            61  102  745
Ajay Singh             26  109  745
Tom McCuch             12   77  745
Michael Aube           17   57  744
Olivier Renault        34   90  744
Jean-Philippe Player   17  106  743
Mark Lochbihler        11  105  742
Rohit Bakshi           32   92  741
Dan Rice               18   95  741
George Vetticaden      23   85  730
Jamie Engesser         19   98  686

In [17]:
### SORT BY INDEX

ordenada.sort_index()

                      min  max  len
driverName
Adam Diaz              26   93  745
Adis Cesir             15   56  746
Ajay Singh             26  109  745
Chris Harris           20   79  746
Dan Rice               18   95  741
Don Hilborn            61  102  745
Eric Mizell            15   97  748
George Vetticaden      23   85  730
Grant Liu              11  104  751
Jamie Engesser         19   98  686
Jean-Philippe Player   17  106  743
Jeff Markham           21  109  748
Joe Niemiec            10   89  746
Mark Lochbihler        11  105  742
Michael Aube           17   57  744
Nadeem Asghar          24   87  749
Olivier Renault        34   90  744
Paul Codding           22  104  746
Rohit Bakshi           32   92  741
Rommel Garcia          18   86  747
Ryan Templeton         21   84  747
Teddy Choi             16  108  750
Tom McCuch             12   77  745

In [20]:
### Se puede ordenar por más de una columna

ordenada.sort_values(by=['min', 'len'])

                      min  max  len
driverName
Joe Niemiec            10   89  746
Mark Lochbihler        11  105  742
Grant Liu              11  104  751
Tom McCuch             12   77  745
Adis Cesir             15   56  746
Eric Mizell            15   97  748
Teddy Choi             16  108  750
Jean-Philippe Player   17  106  743
Michael Aube           17   57  744
Dan Rice               18   95  741
Rommel Garcia          18   86  747
Jamie Engesser         19   98  686
Chris Harris           20   79  746
Ryan Templeton         21   84  747
Jeff Markham           21  109  748
Paul Codding           22  104  746
George Vetticaden      23   85  730
Nadeem Asghar          24   87  749
Adam Diaz              26   93  745
Ajay Singh             26  109  745
Rohit Bakshi           32   92  741
Olivier Renault        34   90  744
Don Hilborn            61  102  745